mri: build 3.x rubies with ruby 3.4.1
Because of this error while building ruby 2.7.8:

    /usr/local/rake-compiler/sources/ruby-2.7.8/lib/delegate.rb:44:in 'Module#undef_method': undefined method '=~' for module '#<Module:0x00007bf99fa388f0>' (NameError)